comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true

coverage:
  ignore:
    - "gen/"
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto