name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark:
    if: github.head_ref == 'jh/bench'
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: benchmark-results
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run benchmark
        run: go test -bench=. ./... | tee output.txt

      - name: Set benchmark directory
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "BENCHMARK_DIR=benchmark_results/main" >> "$GITHUB_ENV"
          else
            echo "BENCHMARK_DIR=benchmark_results/${{ github.head_ref }}" >> "$GITHUB_ENV"
          fi

      - name: If pull request, branch off of the `benchmark_results/main` folder on the `benchmark-results` branch
        if: github.event_name == 'pull_request'
        run: |
          if [ ! -d "$BENCHMARK_DIR" ]; then
            echo "Creating new directory: $BENCHMARK_DIR"
            mkdir -p $BENCHMARK_DIR
            cp -r benchmark_results/main/* "$BENCHMARK_DIR"/
            git add benchmark_results/
            git commit -m "Append benchmark results"
            git push origin benchmark-results
          else
            echo "Directory already exists: $BENCHMARK_DIR"
          fi
          
      - name: Save benchmark data
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: output.txt
          fail-on-alert: true
          alert-threshold: "10%"
          ref: ${{ github.ref }}
          gh-pages-branch: benchmark-results
          benchmark-data-dir-path: ${{ env.BENCHMARK_DIR }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
