name: Benchmark
on:
  push:
    branches:
      - main
      - jh/bench

  jobs:
    benchmark:
      name: Benchmark
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-gov4