name: Integration Test (fraud-template)

on: push

jobs:
  test_integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: ./go.mod

      - name: Run integration tests
        run: |
          go test -v $GITHUB_WORKSPACE/internal/tests/integration
        env:
          INTEGRATION_TESTER: "true"
          CHALK_ACTIVE_ENVIRONMENT: ${{ secrets.CHALK_ACTIVE_ENVIRONMENT }}
          CHALK_CLIENT_ID: ${{ secrets.CHALK_CLIENT_ID }}
          CHALK_CLIENT_SECRET: ${{ secrets.CHALK_CLIENT_SECRET }}
          CHALK_API_SERVER: ${{ secrets.CHALK_API_SERVER }}
          CHALK_USE_CHECKED_ALLOCATOR: 1
